import winreg

HKCU = winreg.HKEY_CURRENT_USER
HKLM = winreg.HKEY_LOCAL_MACHINE

EXPLORER_ADV = r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced"
PERSONALIZE = r"Software\Microsoft\Windows\CurrentVersion\Themes\Personalize"
SEARCH = r"Software\Microsoft\Windows\CurrentVersion\Search"
CLIPBOARD = r"Software\Microsoft\Clipboard"
ADINFO = r"Software\Microsoft\Windows\CurrentVersion\AdvertisingInfo"
CLASSIC_MENU_CLSID = r"Software\Classes\CLSID\{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}\InprocServer32"


TWEAKS = [
    {
        "id": "hidden_files",
        "category": "Проводник",
        "name": "Показывать скрытые файлы",
        "desc": "Файлы с атрибутом «скрытый» станут видимыми",
        "hive": HKCU, "path": EXPLORER_ADV, "value": "Hidden",
        "on": (1, winreg.REG_DWORD),
        "off": (2, winreg.REG_DWORD),
        "restart": "explorer",
    },
    {
        "id": "file_ext",
        "category": "Проводник",
        "name": "Показывать расширения файлов",
        "desc": "Вместо file будет file.txt",
        "hive": HKCU, "path": EXPLORER_ADV, "value": "HideFileExt",
        "on": (0, winreg.REG_DWORD),
        "off": (1, winreg.REG_DWORD),
        "restart": "explorer",
    },
    {
        "id": "this_pc",
        "category": "Проводник",
        "name": "Открывать «Этот компьютер»",
        "desc": "Вместо «Быстрого доступа» при открытии проводника",
        "hive": HKCU, "path": EXPLORER_ADV, "value": "LaunchTo",
        "on": (1, winreg.REG_DWORD),
        "off": (2, winreg.REG_DWORD),
        "restart": "explorer",
    },
    {
        "id": "compact_mode",
        "category": "Проводник",
        "name": "Компактный режим",
        "desc": "Меньше отступы между файлами",
        "hive": HKCU, "path": EXPLORER_ADV, "value": "UseCompactMode",
        "on": (1, winreg.REG_DWORD),
        "off": (0, winreg.REG_DWORD),
        "restart": "explorer",
    },
    {
        "id": "classic_menu",
        "category": "Проводник",
        "name": "Классическое контекстное меню (Win11)",
        "desc": "Полное меню вместо урезанного нового",
        "hive": HKCU, "path": CLASSIC_MENU_CLSID, "value": "",
        "on": ("", winreg.REG_SZ),
        "off": None,
        "restart": "explorer",
    },
    {
        "id": "clock_seconds",
        "category": "Панель задач",
        "name": "Секунды в часах",
        "desc": "Часы на панели задач показывают секунды",
        "hive": HKCU, "path": EXPLORER_ADV, "value": "ShowSecondsInSystemClock",
        "on": (1, winreg.REG_DWORD),
        "off": (0, winreg.REG_DWORD),
        "restart": "explorer",
    },
    {
        "id": "hide_search",
        "category": "Панель задач",
        "name": "Скрыть поиск",
        "desc": "Убирает поисковую строку с панели задач",
        "hive": HKCU, "path": SEARCH, "value": "SearchboxTaskbarMode",
        "on": (0, winreg.REG_DWORD),
        "off": (2, winreg.REG_DWORD),
        "restart": "explorer",
    },
    {
        "id": "hide_widgets",
        "category": "Панель задач",
        "name": "Скрыть виджеты",
        "desc": "Убирает кнопку виджетов",
        "hive": HKCU, "path": EXPLORER_ADV, "value": "TaskbarDa",
        "on": (0, winreg.REG_DWORD),
        "off": (1, winreg.REG_DWORD),
        "restart": "explorer",
    },
    {
        "id": "hide_copilot",
        "category": "Панель задач",
        "name": "Скрыть Copilot",
        "desc": "Убирает кнопку Copilot",
        "hive": HKCU, "path": EXPLORER_ADV, "value": "ShowCopilotButton",
        "on": (0, winreg.REG_DWORD),
        "off": (1, winreg.REG_DWORD),
        "restart": "explorer",
    },
    {
        "id": "taskbar_left",
        "category": "Панель задач",
        "name": "Панель задач слева",
        "desc": "Кнопка «Пуск» и иконки слева (Win11)",
        "hive": HKCU, "path": EXPLORER_ADV, "value": "TaskbarAl",
        "on": (0, winreg.REG_DWORD),
        "off": (1, winreg.REG_DWORD),
        "restart": "explorer",
    },
    {
        "id": "dark_apps",
        "category": "Внешний вид",
        "name": "Тёмная тема приложений",
        "desc": "Тёмный режим для программ",
        "hive": HKCU, "path": PERSONALIZE, "value": "AppsUseLightTheme",
        "on": (0, winreg.REG_DWORD),
        "off": (1, winreg.REG_DWORD),
        "restart": "explorer",
    },
    {
        "id": "dark_system",
        "category": "Внешний вид",
        "name": "Тёмная тема системы",
        "desc": "Тёмный режим для панели задач, Пуска, меню",
        "hive": HKCU, "path": PERSONALIZE, "value": "SystemUsesLightTheme",
        "on": (0, winreg.REG_DWORD),
        "off": (1, winreg.REG_DWORD),
        "restart": "explorer",
    },
    {
        "id": "transparency",
        "category": "Внешний вид",
        "name": "Прозрачность",
        "desc": "Эффекты прозрачности и акрил",
        "hive": HKCU, "path": PERSONALIZE, "value": "EnableTransparency",
        "on": (1, winreg.REG_DWORD),
        "off": (0, winreg.REG_DWORD),
        "restart": "explorer",
    },
    {
        "id": "clipboard_history",
        "category": "Приватность",
        "name": "История буфера обмена",
        "desc": "Win+V — история скопированного",
        "hive": HKCU, "path": CLIPBOARD, "value": "EnableClipboardHistory",
        "on": (1, winreg.REG_DWORD),
        "off": (0, winreg.REG_DWORD),
        "restart": None,
    },
    {
        "id": "disable_adid",
        "category": "Приватность",
        "name": "Отключить рекламный ID",
        "desc": "Приложения не используют ID для рекламы",
        "hive": HKCU, "path": ADINFO, "value": "Enabled",
        "on": (0, winreg.REG_DWORD),
        "off": (1, winreg.REG_DWORD),
        "restart": None,
    },
    {
        "id": "disable_bing",
        "category": "Приватность",
        "name": "Отключить Bing в поиске",
        "desc": "Поиск в Пуске ищет только по локальным файлам",
        "hive": HKCU, "path": SEARCH, "value": "BingSearchEnabled",
        "on": (0, winreg.REG_DWORD),
        "off": (1, winreg.REG_DWORD),
        "restart": "explorer",
    },
]